server:
  port: 8080 
spring:
  datasource:
    url: ENC(GFckA1OjnukCpZC6bDftDSUH8L4aUduRfukh/TIJ+xvXCWg9mvxFCnUE028Gn2P0Q9oeDcj0rik=) 
    driver-class-name: org.mariadb.jdbc.Driver
    username: matthew
    password: ENC(2CTYlgRXmYmlDbJkE9dMV9JQnEAnxNWL)
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: validate 
  sql:
    init:
      mode: never
      platform: mariadb
mybatis:
    mapper-locations: classpath:mybatis/mapper/mariadb/**/**.xml
    type-handlers-package: dev.ohhoonim.demo.mapper.typehandler
    type-aliases-package: dev.ohhoonim.demo.model
    configuration:
        map-underscore-to-camel-case: true
        default-statement-timeout: 30
        default-fetch-size: 100
logging:
    level:
        root: INFO
        dev.ohhoonim.demo.mapper: TRACE