server:
  port: 8080 
spring:
  datasource:
    url: ENC(GFckA1OjnukCpZC6bDftDSUH8L4aUduRfukh/TIJ+xvXCWg9mvxFCnUE028Gn2P0Q9oeDcj0rik=) 
    driver-class-name: org.mariadb.jdbc.Driver
    username: matthew
    password: ENC(2CTYlgRXmYmlDbJkE9dMV9JQnEAnxNWL)
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop

